# Generated by Django 5.1.1 on 2025-09-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_budget_date_alter_expense_date_and_more'),
        ('core', '0002_alter_productionorder_client_add_custom_description'),
    ]

    operations = [
    ]
